from flask import Flask, jsonify, render_template, request
import json

app = Flask(__name__)

# Sample FAQs about sustainability
faqs = [
    {"question": "What is sustainability?", "answer": "Sustainability is the practice of meeting our own needs without compromising the ability of future generations to meet their own needs."},
    {"question": "Why is recycling important?", "answer": "Recycling helps reduce waste, saves energy, conserves natural resources, and reduces pollution."},
    {"question": "What are renewable energy sources?", "answer": "Renewable energy sources include solar, wind, hydroelectric, geothermal, and biomass."},
    {"question": "How can I reduce my carbon footprint?", "answer": "You can reduce your carbon footprint by using public transportation, recycling, conserving energy, and supporting sustainable products."},
    {"question": "What is the greenhouse effect?", "answer": "The greenhouse effect is the warming of Earth's surface caused by the trapping of heat by greenhouse gases in the atmosphere."},
    {"question": "What are the 3 pillars of sustainability?", "answer": "The three pillars of sustainability are environmental protection, economic viability, and social equity."},
    {"question": "How does deforestation impact the environment?", "answer": "Deforestation leads to loss of biodiversity, disrupts water cycles, contributes to climate change, and affects indigenous communities."},
    {"question": "What is the role of biodiversity in sustainability?", "answer": "Biodiversity is essential for ecosystem health, providing resources for food, medicine, and ecosystem services like pollination."},
    {"question": "What are the benefits of using public transport?", "answer": "Public transport reduces traffic congestion, lowers greenhouse gas emissions, and saves energy."},
    {"question": "How can individuals promote sustainability at home?", "answer": "Individuals can promote sustainability by conserving energy, reducing waste, recycling, and using sustainable products."},
    {"question": "What is carbon neutrality?", "answer": "Carbon neutrality means balancing emitted carbon with an equivalent amount of carbon offsets or reductions."},
    {"question": "Why is water conservation important?", "answer": "Water conservation is important to ensure a sustainable supply of clean water for future generations and to protect ecosystems."},
    {"question": "What is organic farming?", "answer": "Organic farming is an agricultural system that avoids synthetic fertilizers and pesticides, focusing on natural processes."},
    {"question": "What is composting?", "answer": "Composting is the process of decomposing organic waste into nutrient-rich soil amendments."},
    {"question": "How does climate change affect weather patterns?", "answer": "Climate change leads to more extreme weather events, changing rainfall patterns, and rising temperatures."},
    {"question": "What is an ecological footprint?", "answer": "An ecological footprint measures the environmental impact of a person, community, or organization in terms of land and resources."},
    {"question": "What are some ways to support sustainable agriculture?", "answer": "Support local farmers, buy organic produce, and reduce meat consumption."},
    {"question": "What is the impact of plastic pollution?", "answer": "Plastic pollution harms wildlife, disrupts ecosystems, and poses health risks to humans."},
    {"question": "How can I make my home more energy-efficient?", "answer": "Use energy-efficient appliances, seal leaks, and improve insulation."},
    {"question": "What are the benefits of eating less meat?", "answer": "Eating less meat can reduce greenhouse gas emissions, conserve water, and improve health."},
    {"question": "What is sustainable transportation?", "answer": "Sustainable transportation includes walking, cycling, carpooling, and using public transit."},
    {"question": "How does urban planning impact sustainability?", "answer": "Good urban planning can reduce sprawl, enhance public transport, and create green spaces."},
    {"question": "What is the circular economy?", "answer": "The circular economy is an economic model that focuses on sustainability, aiming to keep resources in use for as long as possible."},
    {"question": "What are the effects of overfishing?", "answer": "Overfishing leads to depleted fish stocks, disrupted marine ecosystems, and loss of livelihoods for fishing communities."},
    {"question": "How can businesses promote sustainability?", "answer": "Businesses can reduce waste, use sustainable materials, and engage in ethical sourcing."},
    {"question": "What is the significance of the Paris Agreement?", "answer": "The Paris Agreement is a global pact to combat climate change and limit global warming to well below 2 degrees Celsius."},
    {"question": "How can I get involved in local sustainability initiatives?", "answer": "Join local environmental groups, participate in community cleanups, and advocate for sustainable policies."},
    {"question": "What are some eco-friendly home improvements?", "answer": "Install solar panels, use rainwater harvesting, and choose sustainable materials."},
    {"question": "What is climate justice?", "answer": "Climate justice is the idea that those who are least responsible for climate change are often the most affected by its consequences."},
    {"question": "How can I reduce waste in my daily life?", "answer": "Practice the 3 R's: Reduce, Reuse, and Recycle."},
    {"question": "What is a sustainable lifestyle?", "answer": "A sustainable lifestyle minimizes environmental impact and promotes conservation and responsible consumption."},
    {"question": "What are some examples of green building practices?", "answer": "Green building practices include using energy-efficient designs, sustainable materials, and water conservation techniques."},
    {"question": "How does climate change affect food security?", "answer": "Climate change can disrupt food production, affect crop yields, and increase food prices."},
    {"question": "What is the role of technology in sustainability?", "answer": "Technology can enhance efficiency, promote renewable energy, and facilitate sustainable practices."},
    {"question": "How can I encourage others to live sustainably?", "answer": "Lead by example, share information, and support community initiatives."},
    {"question": "What is the significance of biodiversity conservation?", "answer": "Biodiversity conservation helps maintain ecosystem balance and provides resilience against environmental changes."},
    {"question": "How can I support sustainable fashion?", "answer": "Buy from ethical brands, choose second-hand clothing, and support local artisans."},
    {"question": "What is the difference between climate change and global warming?", "answer": "Global warming refers specifically to the Earth's rising surface temperature, while climate change includes global warming and its impacts."},
    {"question": "What are some sustainable gardening practices?", "answer": "Use organic methods, grow native plants, and practice crop rotation."},
    {"question": "What is environmental education?", "answer": "Environmental education aims to increase awareness and knowledge about environmental issues."},
    {"question": "How can technology help in waste management?", "answer": "Technology can optimize recycling processes and provide solutions for waste reduction and management."},
    {"question": "What are the benefits of local food systems?", "answer": "Local food systems support community economies, reduce transportation emissions, and provide fresher food."},
    {"question": "How does climate change impact wildlife?", "answer": "Climate change alters habitats, affects migration patterns, and threatens species survival."},
    {"question": "What is greenwashing?", "answer": "Greenwashing is when a company falsely promotes its products as environmentally friendly."},
    {"question": "How can I start composting at home?", "answer": "Begin composting by collecting organic waste and using a compost bin or pile to decompose it naturally."},
    {"question": "What are some common renewable energy technologies?", "answer": "Common renewable energy technologies include solar panels, wind turbines, and bioenergy systems."},
    {"question": "What is the role of forests in sustainability?", "answer": "Forests provide oxygen, habitat, and resources while regulating climate and water cycles."},
    {"question": "What is the importance of protecting wetlands?", "answer": "Wetlands filter pollutants, provide wildlife habitat, and mitigate flooding."},
    {"question": "How can I participate in Earth Day activities?", "answer": "You can participate in Earth Day activities by volunteering for local cleanups, planting trees, and spreading awareness."},
    {"question": "What are the benefits of community gardens?", "answer": "Community gardens provide fresh produce, foster community engagement, and promote biodiversity."},
    {"question": "What is eco-tourism?", "answer": "Eco-tourism is responsible travel to natural areas that conserves the environment and improves the well-being of local people."},
    {"question": "How can I reduce energy consumption in my home?", "answer": "Turn off lights when not in use, use energy-efficient appliances, and utilize natural light."},
    {"question": "What are the effects of air pollution on health?", "answer": "Air pollution can cause respiratory problems, heart disease, and other serious health issues."},
    {"question": "What is the role of youth in sustainability?", "answer": "Youth play a crucial role in driving change, advocating for sustainable practices, and leading community initiatives."},
    {"question": "What is a zero-waste lifestyle?", "answer": "A zero-waste lifestyle aims to minimize waste by rethinking consumption and making sustainable choices."},
    {"question": "How can we promote sustainable tourism?", "answer": "Promote sustainable tourism by supporting local businesses, respecting natural habitats, and minimizing waste."},
    {"question": "What are the effects of climate change on oceans?", "answer": "Climate change leads to ocean acidification, rising sea levels, and disrupted marine ecosystems."},
    {"question": "How can I find eco-friendly products?", "answer": "Look for certifications like Fair Trade, organic, or products made from recycled materials."},
    {"question": "What is the impact of fast fashion on the environment?", "answer": "Fast fashion contributes to waste, pollution, and exploitation of workers in developing countries."},
    {"question": "How can I reduce plastic use in my daily life?", "answer": "Use reusable bags, bottles, and containers, and avoid single-use plastics."},
    {"question": "What is sustainable fisheries management?", "answer": "Sustainable fisheries management involves practices that ensure fish populations remain healthy and ecosystems intact."},
    {"question": "What role do governments play in sustainability?", "answer": "Governments can implement policies, regulations, and incentives that promote sustainable practices and conservation."},
    {"question": "How does urban sprawl affect sustainability?", "answer": "Urban sprawl leads to habitat loss, increased pollution, and inefficient resource use."},
    {"question": "What is the significance of the United Nations Sustainable Development Goals?", "answer": "The UN Sustainable Development Goals provide a framework for global development, aiming to end poverty and protect the planet."},
    {"question": "How can I support renewable energy initiatives?", "answer": "Support renewable energy initiatives by choosing green energy providers and advocating for clean energy policies."},
    {"question": "What are some sustainable packaging alternatives?", "answer": "Sustainable packaging alternatives include biodegradable materials, recycled paper, and reusable containers."},
    {"question": "What is the importance of soil health in sustainability?", "answer": "Healthy soil is essential for food production, carbon storage, and water filtration."},
    {"question": "How does sustainable architecture benefit the environment?", "answer": "Sustainable architecture reduces energy consumption, utilizes renewable resources, and minimizes waste."},
    {"question": "What are the benefits of tree planting?", "answer": "Tree planting improves air quality, provides habitat, and helps combat climate change."},
    {"question": "How can businesses reduce their environmental impact?", "answer": "Businesses can reduce their environmental impact by improving efficiency, reducing waste, and sourcing sustainably."},
    {"question": "What is the role of NGOs in promoting sustainability?", "answer": "NGOs raise awareness, advocate for policy changes, and implement sustainable projects."},
    {"question": "What is sustainable investment?", "answer": "Sustainable investment considers environmental, social, and governance factors alongside financial returns."},
    {"question": "How can I teach my children about sustainability?", "answer": "Teach your children about sustainability through hands-on activities, discussions, and leading by example."},
    {"question": "What are some benefits of green roofs?", "answer": "Green roofs improve insulation, reduce urban heat, and provide habitats for wildlife."},
    {"question": "How does transportation contribute to climate change?", "answer": "Transportation is a major source of greenhouse gas emissions, primarily from fossil fuel combustion."},
    {"question": "What is sustainable fisheries?", "answer": "Sustainable fisheries manage fish stocks to ensure their health and the health of marine ecosystems."},
    {"question": "How can we address food waste?", "answer": "We can address food waste by planning meals, donating excess food, and composting scraps."},
    {"question": "What are some examples of community-led sustainability projects?", "answer": "Examples include community gardens, local clean-up events, and renewable energy cooperatives."},
    {"question": "How does climate change affect human health?", "answer": "Climate change can exacerbate health issues, lead to food and water insecurity, and increase exposure to diseases."},
    {"question": "What is the importance of environmental legislation?", "answer": "Environmental legislation sets standards for pollution control, resource management, and conservation efforts."},
    {"question": "What are the benefits of sustainable agriculture?", "answer": "Sustainable agriculture enhances soil health, conserves water, and supports local economies."},
    {"question": "How does energy efficiency benefit the environment?", "answer": "Energy efficiency reduces energy consumption, decreases greenhouse gas emissions, and saves resources."},
    {"question": "What is the significance of clean water access?", "answer": "Access to clean water is essential for health, agriculture, and economic development."},
    {"question": "How can we promote environmental awareness?", "answer": "Promote environmental awareness through education, community events, and social media."},
    {"question": "What is the impact of climate change on agriculture?", "answer": "Climate change affects crop yields, alters growing seasons, and increases pests and diseases."},
    {"question": "How does waste-to-energy technology work?", "answer": "Waste-to-energy technology converts non-recyclable waste materials into usable heat, electricity, or fuel."},
    {"question": "What are the benefits of green spaces in urban areas?", "answer": "Green spaces improve air quality, provide recreational areas, and support biodiversity."},
    {"question": "What role do individuals play in sustainability?", "answer": "Individuals can make sustainable choices, advocate for change, and educate others about environmental issues."}
]
